### ISSUE TITLE
Update readme with latest project status

### ISSUE THREAD

**Issue by aral** [webOS-ports/meta-pine64-luneos#23]
From [the releases page](https://github.com/webOS-ports/meta-pine64-luneos/releases), it sounds like a lot of work has gone into this since the readme was written and that the limitations listed there are no longer present (at least in the PinePhone build).

Would be good to reflect the current status in the readme to create a better first impression.

(And thank you for keeping on with this. It has so much potential.) 💕

**Comment by Tofee** [comment]
https://github.com/webOS-ports/meta-pine64-luneos/pull/24 has been merged.
